-- ============================================================================
-- CARGA INICIAL (gerada de src/data/seed.json em 2026-09-03T18:18:08.646Z)
-- Origem: planilha Fluxo_de_Caixa_EIFF.xlsx | data-base 2026-09-01 | cenario Base
-- ============================================================================
insert into organization (code, name) values ('EIFF', 'EIFF') on conflict (code) do nothing;
insert into company (organization_id, code, name) values ((select id from organization where code = 'EIFF'), 'EIFF', 'EIFF Engenharia') on conflict (organization_id, code) do nothing;

insert into parameter_set (organization_id, base_date, scenario, include_demo, min_reserve, limit_project_manager, limit_finance, limit_board,
  budget_deviation_allowed, reconciliation_tolerance, approval_sla_hours, responsible, version)
select (select id from organization where code = 'EIFF'), '2026-09-01', 'Base', false, 0,
  20000, 100000, 100000,
  0.05, 0.01, 48,
  'Diretoria Financeira', '1.0 — Implantação'
where not exists (select 1 from parameter_set where organization_id = (select id from organization where code = 'EIFF') and active);
insert into scenario_factor (parameter_set_id, scenario, inflow_factor, outflow_factor)
select id, 'Conservador', 0.85, 1.05 from parameter_set where organization_id = (select id from organization where code = 'EIFF') and active
on conflict (parameter_set_id, scenario) do nothing;
insert into scenario_factor (parameter_set_id, scenario, inflow_factor, outflow_factor)
select id, 'Base', 1, 1 from parameter_set where organization_id = (select id from organization where code = 'EIFF') and active
on conflict (parameter_set_id, scenario) do nothing;
insert into scenario_factor (parameter_set_id, scenario, inflow_factor, outflow_factor)
select id, 'Otimista', 1.1, 0.95 from parameter_set where organization_id = (select id from organization where code = 'EIFF') and active
on conflict (parameter_set_id, scenario) do nothing;

-- plano de contas
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Sinais e adiantamentos', 'Entrada', 'Receitas Operacionais', 'Receita Operacional', 'Operacional', 'Entradas antecipadas de clientes', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Medições de obras', 'Entrada', 'Receitas Operacionais', 'Receita Operacional', 'Operacional', 'Recebimentos vinculados a medição', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Parcelas contratuais', 'Entrada', 'Receitas Operacionais', 'Receita Operacional', 'Operacional', 'Parcelas previstas em contrato', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Projetos e engenharia', 'Entrada', 'Receitas Operacionais', 'Receita Operacional', 'Operacional', 'Projetos, detalhamento e engenharia', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Venda de estruturas e materiais', 'Entrada', 'Receitas Operacionais', 'Receita Operacional', 'Operacional', 'Estruturas, perfis e materiais', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Serviços de montagem', 'Entrada', 'Receitas Operacionais', 'Receita Operacional', 'Operacional', 'Montagem e instalação', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Reembolsos', 'Entrada', 'Outras Entradas', 'Outras Receitas Operacionais', 'Operacional', 'Reembolsos de despesas', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Empréstimos recebidos', 'Entrada', 'Financiamento e Capital', 'Não DRE', 'Financiamento', 'Captação de dívida', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Aportes de sócios', 'Entrada', 'Financiamento e Capital', 'Não DRE', 'Capital', 'Aporte de capital', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Venda de ativos', 'Entrada', 'Outras Entradas', 'Outras Receitas', 'Não operacional', 'Alienação de ativos', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Outros recebimentos', 'Entrada', 'Outras Entradas', 'Outras Receitas Operacionais', 'Operacional', 'Demais entradas de caixa', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Aço e perfis', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Perfis laminados, soldados e conformados', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Chapas, telhas e painéis', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Chapas, coberturas e fechamentos', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Concreto e fundações', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Infraestrutura e fundações', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Componentes e fixadores', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Parafusos, consumíveis e componentes', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Mão de obra terceirizada', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Fabricação, montagem e equipes terceiras', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Transporte e mobilização', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Fretes, guindastes e mobilização', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Equipamentos e locações', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Locações aplicadas às obras', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Projetos, ART e licenças', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Projetos, responsabilidade técnica e taxas', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Instalações e acabamentos', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Instalações e acabamentos contratados', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Outros custos diretos', 'Saída', 'Custos Diretos de Obras', 'Custos Diretos', 'Custo direto', 'Demais custos vinculados à obra', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Folha e salários', 'Saída', 'Despesas com Pessoal', 'Despesas com Pessoal', 'Despesa indireta', 'Folha mensal', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Pró-labore', 'Saída', 'Despesas com Pessoal', 'Despesas com Pessoal', 'Despesa indireta', 'Pró-labore da administração', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Encargos e benefícios', 'Saída', 'Despesas com Pessoal', 'Despesas com Pessoal', 'Despesa indireta', 'Encargos, benefícios e provisões', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Aluguel e condomínio', 'Saída', 'Despesas Administrativas', 'Despesas Administrativas', 'Despesa indireta', 'Imóveis administrativos e fabris', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Energia, água e internet', 'Saída', 'Despesas Administrativas', 'Despesas Administrativas', 'Despesa indireta', 'Utilidades', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Contabilidade e jurídico', 'Saída', 'Despesas Administrativas', 'Despesas Administrativas', 'Despesa indireta', 'Serviços profissionais', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Seguros', 'Saída', 'Despesas Administrativas', 'Despesas Administrativas', 'Despesa indireta', 'Seguros corporativos e de obras', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Tecnologia e software', 'Saída', 'Despesas Administrativas', 'Despesas Administrativas', 'Despesa indireta', 'Licenças e sistemas', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Marketing e tráfego', 'Saída', 'Despesas Comerciais', 'Despesas Comerciais', 'Despesa indireta', 'Aquisição de demanda', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Comissões', 'Saída', 'Despesas Comerciais', 'Despesas Comerciais', 'Despesa indireta', 'Comissões de vendas', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Viagens e representação', 'Saída', 'Despesas Comerciais', 'Despesas Comerciais', 'Despesa indireta', 'Visitas, viagens e representação', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Veículos e combustível', 'Saída', 'Despesas Operacionais', 'Despesas Operacionais', 'Despesa indireta', 'Frota e deslocamentos', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Manutenção', 'Saída', 'Despesas Operacionais', 'Despesas Operacionais', 'Despesa indireta', 'Manutenção fabril e geral', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Segurança e limpeza', 'Saída', 'Despesas Operacionais', 'Despesas Operacionais', 'Despesa indireta', 'Serviços de apoio', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Impostos sobre faturamento', 'Saída', 'Tributos', 'Deduções da Receita', 'Tributo', 'Tributos incidentes sobre receita', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Tributos e taxas gerais', 'Saída', 'Tributos', 'Tributos', 'Tributo', 'Tributos não vinculados diretamente ao faturamento', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Juros e tarifas bancárias', 'Saída', 'Serviço da Dívida', 'Resultado Financeiro', 'Financeiro', 'Juros, IOF e tarifas', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Amortização de dívidas', 'Saída', 'Serviço da Dívida', 'Não DRE', 'Financiamento', 'Principal de empréstimos e financiamentos', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Máquinas e equipamentos', 'Saída', 'Investimentos', 'Não DRE', 'Investimento', 'CAPEX produtivo', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Obras e benfeitorias', 'Saída', 'Investimentos', 'Não DRE', 'Investimento', 'CAPEX em instalações', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Distribuição de lucros', 'Saída', 'Outras Saídas', 'Não DRE', 'Capital', 'Distribuições aos sócios', true) on conflict (organization_id, category) do nothing;
insert into chart_account (organization_id, category, entry_type, cash_group, dre_group, account_class, guidance, active) values ((select id from organization where code = 'EIFF'), 'Outros pagamentos', 'Saída', 'Outras Saídas', 'Outras Despesas', 'Não operacional', 'Demais saídas de caixa', true) on conflict (organization_id, category) do nothing;

-- contas financeiras
insert into bank_account (organization_id, company_id, code, record_kind, institution, account_label, account_type, opening_balance, opening_balance_date, linked_reserve, active) values ((select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'CTA-001', 'Real', 'Caixa', 'Caixa disponível', 'Caixa', 11544.48, '2026-09-01', 0, true) on conflict (organization_id, code) do nothing;

-- obras
insert into project (organization_id, company_id, code, record_kind, name, client_name, city_state, status, scope, signed_at, starts_at, contractual_end, contract_value, addenda_value, budgeted_cost, physical_progress, measured_invoiced, estimate_to_complete, notes, source_system, external_id)
values ((select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'OB-SF-CL-01', 'Real', 'Smart Fit - Avenida César Lattes', 'Invest Market Construção Sob Medida Ltda ME', 'Goiânia / GO', 'Em execução', 'Execução da unidade Smart Fit em regime de empreitada global Turn Key', null, null, null, 1291500, 0, 0, 0, 157975, 0, 'Fontes: espelho/planilha de medição de 01/09/2026 e fluxo de recebimentos informado pelo usuário. Receita própria MODO; faturamento direto excluído.', 'planilha', 'OB-SF-CL-01')
on conflict (organization_id, code) do nothing;

-- lancamentos
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-001', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Invest Market Construção Sob Medida Ltda ME', 'NF 47', 'Medição aprovada E03, E05, E06 e E07 - NF 47 MODO', '2026-09-01', '2026-09-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 157975, 7898.75, 0, 0, 0, false, 'Fonte: NF 47 e espelho de medição aprovados em 01/09/2026.', 'planilha', 'REC-SF-CL-001')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-002', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-002', 'Receita prevista - mão de obra - ago/26', '2026-08-10', '2026-08-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 193975, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-002')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-003', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-003', 'Receita prevista - mão de obra - set/26', '2026-09-10', '2026-09-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 172000, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-003')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-004', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-004', 'Receita prevista - mão de obra - out/26', '2026-10-10', '2026-10-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 323175, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-004')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-005', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-005', 'Receita prevista - mão de obra - nov/26', '2026-11-10', '2026-11-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 238000, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-005')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-006', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-006', 'Receita prevista - mão de obra - dez/26', '2026-12-10', '2026-12-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 121000, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-006')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-007', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-007', 'Receita prevista - mão de obra - jan/27', '2027-01-10', '2027-01-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 144500, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-007')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-008', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-008', 'Receita prevista - mão de obra - fev/27', '2027-02-10', '2027-02-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 70500, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-008')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-009', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-009', 'Receita prevista - estrutura metálica - set/26', '2026-09-10', '2026-09-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 61818.99, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-009')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-010', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-010', 'Receita prevista - estrutura metálica - out/26', '2026-10-10', '2026-10-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 71091.84, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-010')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-011', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-011', 'Receita prevista - estrutura metálica - nov/26', '2026-11-10', '2026-11-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 103546.81, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-011')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-012', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-012', 'Receita prevista - estrutura metálica - dez/26', '2026-12-10', '2026-12-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 16828.5, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-012')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-013', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-013', 'Receita prevista - pintura estrutura metálica - out/26', '2026-10-10', '2026-10-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 36666.67, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-013')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-014', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-014', 'Receita prevista - pintura estrutura metálica - nov/26', '2026-11-10', '2026-11-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 62333.33, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-014')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-015', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-015', 'Receita prevista - telha isotérmica - dez/26', '2026-12-10', '2026-12-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 66330, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-015')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-016', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-016', 'Receita prevista - concreto piso e laje - nov/26', '2026-11-10', '2026-11-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 16615.38, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-016')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('REC-SF-CL-017', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Entrada', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Medições de obras'), null, 'Obra', (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'Fornecedor a definir', 'REC-SF-CL-017', 'Receita prevista - laje Steel Deck - set/26', '2026-09-10', '2026-09-10', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 104850, 0, 0, 0, 0, false, 'Fonte: fluxo de pagamentos informado pelo usuário em 01/09/2026.', 'planilha', 'REC-SF-CL-017')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2026-09', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2026-09', 'Folha de pagamento - 2026-09 (5º dia útil)', '2026-09-07', '2026-09-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2026-09')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2026-10', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2026-10', 'Folha de pagamento - 2026-10 (5º dia útil)', '2026-10-07', '2026-10-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2026-10')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2026-11', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2026-11', 'Folha de pagamento - 2026-11 (5º dia útil)', '2026-11-06', '2026-11-06', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2026-11')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2026-12', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2026-12', 'Folha de pagamento - 2026-12 (5º dia útil)', '2026-12-07', '2026-12-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2026-12')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-01', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-01', 'Folha de pagamento - 2027-01 (5º dia útil)', '2027-01-07', '2027-01-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-01')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-02', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-02', 'Folha de pagamento - 2027-02 (5º dia útil)', '2027-02-05', '2027-02-05', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-02')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-03', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-03', 'Folha de pagamento - 2027-03 (5º dia útil)', '2027-03-05', '2027-03-05', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-03')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-04', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-04', 'Folha de pagamento - 2027-04 (5º dia útil)', '2027-04-07', '2027-04-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-04')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-05', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-05', 'Folha de pagamento - 2027-05 (5º dia útil)', '2027-05-07', '2027-05-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-05')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-06', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-06', 'Folha de pagamento - 2027-06 (5º dia útil)', '2027-06-07', '2027-06-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-06')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-07', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-07', 'Folha de pagamento - 2027-07 (5º dia útil)', '2027-07-07', '2027-07-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-07')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-08', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-08', 'Folha de pagamento - 2027-08 (5º dia útil)', '2027-08-06', '2027-08-06', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-08')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-09', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-09', 'Folha de pagamento - 2027-09 (5º dia útil)', '2027-09-07', '2027-09-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-09')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-10', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-10', 'Folha de pagamento - 2027-10 (5º dia útil)', '2027-10-07', '2027-10-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-10')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-11', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-11', 'Folha de pagamento - 2027-11 (5º dia útil)', '2027-11-05', '2027-11-05', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-11')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2027-12', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2027-12', 'Folha de pagamento - 2027-12 (5º dia útil)', '2027-12-07', '2027-12-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2027-12')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-01', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-01', 'Folha de pagamento - 2028-01 (5º dia útil)', '2028-01-07', '2028-01-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-01')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-02', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-02', 'Folha de pagamento - 2028-02 (5º dia útil)', '2028-02-07', '2028-02-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-02')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-03', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-03', 'Folha de pagamento - 2028-03 (5º dia útil)', '2028-03-07', '2028-03-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-03')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-04', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-04', 'Folha de pagamento - 2028-04 (5º dia útil)', '2028-04-07', '2028-04-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-04')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-05', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-05', 'Folha de pagamento - 2028-05 (5º dia útil)', '2028-05-05', '2028-05-05', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-05')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-06', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-06', 'Folha de pagamento - 2028-06 (5º dia útil)', '2028-06-07', '2028-06-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-06')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-07', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-07', 'Folha de pagamento - 2028-07 (5º dia útil)', '2028-07-07', '2028-07-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-07')
on conflict (organization_id, code) do nothing;
insert into financial_entry (code, organization_id, company_id, record_kind, entry_type, chart_account_id, sub_category, cost_center_label, project_id, counterparty_name, document_number, description, competence_date, due_date, settlement_date, status, confidence, probability, bank_account_id, gross_amount, tax_amount, discount_amount, interest_amount, settled_amount, reconciled, notes, source_system, external_id)
values ('PAG-FOLHA-2028-08', (select id from organization where code = 'EIFF'), (select id from company where code = 'EIFF' and organization_id = (select id from organization where code = 'EIFF')), 'Real', 'Saída', (select id from chart_account where organization_id = (select id from organization where code = 'EIFF') and category = 'Folha e salários'), null, 'Corporativo', null, 'Colaboradores EIFF', 'FOLHA-2028-08', 'Folha de pagamento - 2028-08 (5º dia útil)', '2028-08-07', '2028-08-07', null, 'Programado', 'Confirmado', 1, (select id from bank_account where organization_id = (select id from organization where code = 'EIFF') and institution = 'Caixa' limit 1), 63220.04, 0, 0, 0, 0, false, 'Folha mensal recorrente: 12 colaboradores | valores informados pelo usuário | dias úteis sem feriados.', 'planilha', 'PAG-FOLHA-2028-08')
on conflict (organization_id, code) do nothing;

-- servicos das obras (derivados das receitas previstas) e vinculo dos lancamentos
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, estimate_to_complete, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'SFCL-01', 'Mão de obra', 'Montagem', 'vb', 1, 0, 0, 1263150, null, '2026-08-01', '2027-02-10', 'Não iniciado', 'Derivado das receitas previstas da planilha; informar custo orçado, quantidades e prazos reais.', true)
on conflict (project_id, code) do nothing;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, estimate_to_complete, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'SFCL-02', 'Estrutura metálica', 'Fabricação', 'vb', 1, 0, 0, 253286.14, null, '2026-09-01', '2026-12-10', 'Não iniciado', 'Derivado das receitas previstas da planilha; informar custo orçado, quantidades e prazos reais.', true)
on conflict (project_id, code) do nothing;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, estimate_to_complete, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'SFCL-03', 'Pintura estrutura metálica', 'Fabricação', 'vb', 1, 0, 0, 99000, null, '2026-10-01', '2026-11-10', 'Não iniciado', 'Derivado das receitas previstas da planilha; informar custo orçado, quantidades e prazos reais.', true)
on conflict (project_id, code) do nothing;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, estimate_to_complete, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'SFCL-04', 'Telha isotérmica', 'Cobertura e fechamento', 'vb', 1, 0, 0, 66330, null, '2026-12-01', '2026-12-10', 'Não iniciado', 'Derivado das receitas previstas da planilha; informar custo orçado, quantidades e prazos reais.', true)
on conflict (project_id, code) do nothing;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, estimate_to_complete, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'SFCL-05', 'Concreto piso e laje', 'Civil', 'vb', 1, 0, 0, 16615.38, null, '2026-11-01', '2026-11-10', 'Não iniciado', 'Derivado das receitas previstas da planilha; informar custo orçado, quantidades e prazos reais.', true)
on conflict (project_id, code) do nothing;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, estimate_to_complete, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01'), 'SFCL-06', 'Laje Steel Deck', 'Civil', 'vb', 1, 0, 0, 104850, null, '2026-09-01', '2026-09-10', 'Não iniciado', 'Derivado das receitas previstas da planilha; informar custo orçado, quantidades e prazos reais.', true)
on conflict (project_id, code) do nothing;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-01') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-002' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-01') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-003' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-01') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-004' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-01') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-005' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-01') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-006' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-01') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-007' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-01') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-008' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-02') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-009' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-02') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-010' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-02') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-011' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-02') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-012' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-03') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-013' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-03') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-014' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-04') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-015' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-05') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-016' and service_id is null;
update financial_entry set service_id = (select id from project_service where project_id = (select id from project where organization_id = (select id from organization where code = 'EIFF') and code = 'OB-SF-CL-01') and code = 'SFCL-06') where organization_id = (select id from organization where code = 'EIFF') and code = 'REC-SF-CL-017' and service_id is null;

-- dividas
