-- Cronograma fisico-financeiro Smart Fit Cesar Lattes (gerado por scripts/cronograma-smartfit.mjs em 2026-09-03)
-- Fonte: 03. CRONOGRAMA FISICO FINANCEIRO.pdf (rev. contraproposta). Retencao 10%; mes 01 = junho/2026.
update project set starts_at = coalesce(starts_at, '2026-06-01'), contractual_end = coalesce(contractual_end, '2027-02-28'), target_margin = coalesce(target_margin, 0.25),
  scope = coalesce(nullif(scope,''), 'Execução da unidade Smart Fit em regime de empreitada global Turn Key') where code = 'OB-SF-CL-01';

-- os servicos SFCL-01..06 derivados da planilha sao substituidos (mesmo codigo) pelas etapas do cronograma;
-- as receitas "mao de obra" perdem o vinculo (nao ha etapa equivalente) e as demais sao religadas pelo nome abaixo
update financial_entry e set service_id = null where e.project_id = (select id from project where code = 'OB-SF-CL-01') and e.description ilike '%mão de obra%';
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-01', 'Projetos executivos', 'Projeto', 'vb', 1, 0, 0, 56700.00, 0.00, 63000, '2026-05-01', '2026-07-31', 'Não iniciado', 'Etapa do cronograma contratual: Projetos Executivos. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-02', 'Administração e mobilização do canteiro', 'Outros', 'vb', 1, 0, 0, 108000.00, 0.00, 72776.94, '2026-07-01', '2026-08-31', 'Não iniciado', 'Etapa do cronograma contratual: Administração / Mobilização. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-03', 'Serviços preliminares e instalações temporárias', 'Civil', 'vb', 1, 0, 0, 46800.00, 30000.00, 63264.55, '2026-07-01', '2026-08-31', 'Não iniciado', 'Etapa do cronograma contratual: Serviços Preliminares. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-04', 'Movimentação de terra e regularização', 'Civil', 'vb', 1, 0, 0, 108000.00, 100000.00, 240473.61, '2026-07-01', '2026-09-30', 'Não iniciado', 'Etapa do cronograma contratual: Movimentação de Terra. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-05', 'Fundação, baldrames e arrimos', 'Civil', 'vb', 1, 0, 0, 151200.00, 50000.00, 557042.7, '2026-07-01', '2026-09-30', 'Não iniciado', 'Etapa do cronograma contratual: Fundação e Arrimo. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-06', 'Estrutura metálica: aço, fabricação e montagem', 'Fabricação', 'vb', 1, 0, 0, 162000.00, 620000.00, 1456563.44, '2026-08-01', '2026-10-31', 'Não iniciado', 'Etapa do cronograma contratual: Estrutura Metálica. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-07', 'Cobertura metálica', 'Cobertura e fechamento', 'vb', 1, 0, 0, 4500.00, 185000.00, 276598.74, '2026-09-01', '2026-10-31', 'Não iniciado', 'Etapa do cronograma contratual: Cobertura. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-08', 'Instalações elétricas, SPDA, hidrossanitárias e incêndio', 'Instalações', 'vb', 1, 0, 0, 67500.00, 260000.00, 350949.89, '2026-09-01', '2026-11-30', 'Não iniciado', 'Etapa do cronograma contratual: Instalações Gerais. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-09', 'Laje steel deck', 'Civil', 'vb', 1, 0, 0, 36000.00, 245000.00, 253057.55, '2026-10-01', '2026-11-30', 'Não iniciado', 'Etapa do cronograma contratual: Steel Deck. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-10', 'Vedação externa (isopainéis e fechamentos)', 'Cobertura e fechamento', 'vb', 1, 0, 0, 31500.00, 220000.00, 281512.68, '2026-10-01', '2026-11-30', 'Não iniciado', 'Etapa do cronograma contratual: Vedação Externa. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-11', 'Logística, transporte e conclusão de montagem', 'Montagem', 'vb', 1, 0, 0, 54000.00, 35000.00, 47016.2, '2026-10-01', '2026-11-30', 'Não iniciado', 'Etapa do cronograma contratual: Estrutura/Cobertura/Transporte. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-12', 'Piso industrial', 'Civil', 'vb', 1, 0, 0, 72000.00, 180000.00, 266693.32, '2026-11-01', '2026-12-31', 'Não iniciado', 'Etapa do cronograma contratual: Piso Industrial. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-13', 'Pintura industrial e demarcações', 'Pintura', 'vb', 1, 0, 0, 49500.00, 150000.00, 244713.48, '2026-11-01', '2026-12-31', 'Não iniciado', 'Etapa do cronograma contratual: Pintura. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-14', 'Instalações finais e arremates', 'Instalações', 'vb', 1, 0, 0, 94500.00, 70000.00, null, '2026-11-01', '2026-12-31', 'Não iniciado', 'Etapa do cronograma contratual: Instalações / Acabamentos. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-15', 'Finalizações e testes operacionais', 'Outros', 'vb', 1, 0, 0, 49500.00, 160000.00, null, '2026-12-01', '2027-01-31', 'Não iniciado', 'Etapa do cronograma contratual: Acabamentos / Testes. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-16', 'Pré-entrega e fechamento de pendências', 'Outros', 'vb', 1, 0, 0, 58500.00, 180000.00, null, '2026-12-01', '2027-01-31', 'Não iniciado', 'Etapa do cronograma contratual: Acabamentos / Pré-entrega. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;
insert into project_service (organization_id, project_id, code, name, phase, unit, budgeted_qty, executed_qty, budgeted_cost, sale_price, sale_direct, budget_base, planned_start, planned_end, status, notes, active)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), 'SFCL-17', 'Entrega técnica, as built e desmobilização', 'Outros', 'vb', 1, 0, 0, 135000.00, 187000.00, 10322.17, '2027-01-01', '2027-02-28', 'Não iniciado', 'Etapa do cronograma contratual: Entrega Final. Preço = faturamento da construtora líquido de retenção (10%).', true)
on conflict (project_id, code) do update set name = excluded.name, phase = excluded.phase, sale_price = excluded.sale_price, sale_direct = excluded.sale_direct, budget_base = excluded.budget_base, planned_start = excluded.planned_start, planned_end = excluded.planned_end, active = true;

-- eventos de medicao
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-01'), 'E01', 'Entrega técnica', '2026-05-01', '2026-06-30', 15750, 'Pendente', 1, 'Projetos Executivos', 'Kickoff, compatibilização inicial e cronograma macro', 'Reunião de partida, matriz de responsabilidades, cronograma macro, levantamento de interferências e diretrizes de suprimentos.', 'Cronograma preliminar e matriz de responsabilidades aprovados.', 'Ata de kickoff, cronograma preliminar, matriz de pendências e relatório técnico inicial.', 'Contratante / Fiscalização', '2026-06-30', 15750, 0, 15750, 1575, 0.0038, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-01'), 'E02', 'Entrega técnica', '2026-05-01', '2026-06-30', 15750, 'Pendente', 1, 'Projetos Executivos', 'Desenvolvimento inicial dos projetos executivos', 'Desenvolvimento das disciplinas executivas, compatibilização inicial e consolidação dos quantitativos preliminares.', 'Projetos em revisão inicial protocolados e compatibilização inicial entregue.', 'Pranchas em revisão, memorial técnico preliminar e relatório de compatibilização.', 'Contratante / Fiscalização', '2026-06-30', 15750, 0, 15750, 1575, 0.0038, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-01'), 'E03', 'Entrega técnica', '2026-06-01', '2026-07-31', 15750, 'Faturado', 2, 'Projetos Executivos', 'Planejamento executivo final e equalização técnica', 'Consolidação do planejamento executivo, planejamento de fabricação, logística, suprimentos e sequenciamento da obra.', 'Planejamento executivo final aprovado.', 'Plano executivo, cronograma atualizado, matriz de fornecedores e planejamento de suprimentos.', 'Contratante / Fiscalização', '2026-07-31', 15750, 0, 15750, 1575, 0.0038, '2026-09-01', (select id from financial_entry where code = 'REC-SF-CL-001'), 'Medido na NF 47 (01/09/2026).')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-01'), 'E04', 'Entrega técnica', '2026-06-01', '2026-07-31', 15750, 'Pendente', 2, 'Projetos Executivos', 'Liberação técnica para produção e mobilização', 'Liberação final de desenhos, diretrizes de fabricação, premissas de montagem e liberação para mobilização.', 'Desenhos liberados para produção/mobilização.', 'Desenhos liberados, relatório de liberação e aceite técnico.', 'Contratante / Fiscalização', '2026-07-31', 15750, 0, 15750, 1575, 0.0038, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-02'), 'E05', 'Evento físico', '2026-07-01', '2026-08-31', 120000, 'Faturado', 3, 'Administração / Mobilização', 'Mobilização do canteiro e administração inicial', 'Implantação do canteiro, containers, ligações provisórias, estrutura de apoio, equipe inicial e gestão operacional.', 'Canteiro funcional implantado.', 'Relatório fotográfico, check-list de mobilização, evidências de canteiro funcional.', 'Fiscalização', '2026-08-31', 120000, 0, 120000, 12000, 0.0293, '2026-09-01', (select id from financial_entry where code = 'REC-SF-CL-001'), 'Medido na NF 47 (01/09/2026).')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-03'), 'E06', 'Evento físico/documental', '2026-07-01', '2026-08-31', 52000, 'Faturado', 3, 'Serviços Preliminares', 'Serviços preliminares e instalações temporárias', 'Locações, proteções, equipamentos iniciais, limpeza, placa de obra, ligações provisórias e apoio operacional.', 'Serviços preliminares executados conforme escopo.', 'Relatório fotográfico, diário de obra e check-list de serviços preliminares.', 'Fiscalização', '2026-08-31', 82000, 30000, 52000, 8200, 0.02, '2026-09-01', (select id from financial_entry where code = 'REC-SF-CL-001'), 'Medido na NF 47 (01/09/2026).')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-04'), 'E07', 'Percentual físico', '2026-07-01', '2026-08-31', 60000, 'Faturado', 3, 'Movimentação de Terra', 'Terraplenagem e regularização inicial', 'Movimentação de terra, aterro, regularização de áreas, preparação de plataformas e infraestrutura inicial.', 'Terraplenagem e regularização executadas conforme frente liberada.', 'Relatório de volume/área executada, fotos, diário de obra e validação topográfica quando aplicável.', 'Fiscalização', '2026-08-31', 110000, 50000, 60000, 11000, 0.0537, '2026-09-01', (select id from financial_entry where code = 'REC-SF-CL-001'), 'Medido na NF 47 (01/09/2026). Contraproposta: terraplenagem dividida 50% M3 e 50% M4.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-05'), 'E08', 'Percentual físico', '2026-07-01', '2026-08-31', 68000, 'Pendente', 3, 'Fundação e Arrimo', 'Fundação inicial', 'Início das estacas, blocos, armaduras, concretagens e liberação parcial para continuidade estrutural.', 'Fundação inicial executada e registrada.', 'Fotos, diário de concretagem, controle tecnológico quando aplicável e relatório de avanço físico.', 'Fiscalização', '2026-08-31', 68000, 0, 68000, 6800, 0.0317, null, null, 'Contraproposta: reduzida de R$ 130k para R$ 68k.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-04'), 'E07b', 'Percentual físico', '2026-08-01', '2026-09-30', 60000, 'Pendente', 4, 'Movimentação de Terra', 'Conclusão da terraplenagem e regularização', 'Conclusão do aterro, regularização de áreas e infraestrutura de plataforma, segunda metade do volume contratado.', 'Volume real executado validado por topografia, 50% restante do aterro contratado.', 'Relatório de volume executado, fotos, diário de obra e validação topográfica.', 'Fiscalização', '2026-09-30', 110000, 50000, 60000, 11000, 0.0268, null, null, 'Contraproposta: segunda metade da terraplenagem.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-05'), 'E09', 'Percentual físico', '2026-08-01', '2026-09-30', 100000, 'Pendente', 4, 'Fundação e Arrimo', 'Conclusão das fundações, baldrames e arrimos', 'Conclusão de estacas, blocos, vigas baldrame, arrimos, armaduras e concretagens estruturais.', 'Fundações, baldrames e arrimos liberados para montagem.', 'Relatório de avanço, fotos, diário de concretagem, check-list de liberação estrutural.', 'Fiscalização', '2026-09-30', 150000, 50000, 100000, 15000, 0.0634, null, null, 'Contraproposta: ajustada para R$ 150k, absorve saldo da fundação inicial.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-06'), 'E10', 'Fornecimento direto', '2026-08-01', '2026-09-30', 0, 'Pendente', 4, 'Estrutura Metálica', 'Compra estratégica de aço e insumos metálicos', 'Aquisição de matéria-prima metálica, perfis, chapas, chumbadores e insumos industriais de fabricação.', 'Compra/reserva de aço e insumos comprovada documentalmente.', 'Pedido de compra, nota fiscal, comprovante de pedido, romaneio ou evidência de reserva/compra.', 'Contratante / Suprimentos', '2026-09-30', 175000, 175000, 0, 17500, 0.0634, null, null, 'Contraproposta: adiantamento de aço reduzido de R$ 260k para R$ 175k. 100% faturamento direto.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-06'), 'E11', 'Fabricação', '2026-08-01', '2026-09-30', 40000, 'Pendente', 4, 'Estrutura Metálica', 'Fabricação industrial da estrutura metálica - fase 01', 'Corte, preparação, soldagem, montagem fabril, chumbadores, peças primárias e controle produtivo.', 'Fabricação fase 01 comprovada por relatório fabril.', 'Relatório fabril, fotos de produção, romaneio parcial e controle de qualidade.', 'Fiscalização / Qualidade', '2026-09-30', 185000, 145000, 40000, 18500, 0.0451, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-06'), 'E12', 'Fabricação', '2026-09-01', '2026-10-31', 30000, 'Pendente', 5, 'Estrutura Metálica', 'Fabricação industrial da estrutura metálica - fase 02', 'Continuidade da fabricação metálica, estrutura secundária, travamentos, preparação para pintura e expedição.', 'Fabricação fase 02 comprovada por relatório fabril.', 'Relatório fabril, fotos, romaneio, controle de qualidade e evidência de avanço produtivo.', 'Fiscalização / Qualidade', '2026-10-31', 230000, 200000, 30000, 23000, 0.0561, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-06'), 'E13', 'Percentual físico', '2026-09-01', '2026-10-31', 110000, 'Pendente', 5, 'Estrutura Metálica', 'Montagem metálica principal', 'Transporte interno, içamento, posicionamento de pórticos, ligações metálicas, alinhamento e travamentos.', 'Montagem metálica principal com avanço físico validado.', 'Relatório fotográfico, diário de montagem, check-list de segurança e avanço físico.', 'Fiscalização', '2026-10-31', 210000, 100000, 110000, 21000, 0.0512, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-07'), 'E14', 'Fornecimento + execução', '2026-09-01', '2026-10-31', 5000, 'Pendente', 5, 'Cobertura', 'Fornecimento e início da cobertura metálica', 'Telhas termoacústicas, calhas, rufos, arremates e início da instalação de cobertura.', 'Materiais de cobertura entregues e início de instalação comprovado.', 'NF/romaneio de materiais, fotos de entrega e instalação, relatório de avanço.', 'Fiscalização', '2026-10-31', 190000, 185000, 5000, 19000, 0.0549, null, null, 'Contraproposta: R$ 35k de cobertura realocados para M6.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-08'), 'E15', 'Percentual físico', '2026-09-01', '2026-10-31', 20000, 'Pendente', 5, 'Instalações Gerais', 'Instalações elétricas e SPDA - fase 01', 'Infraestrutura elétrica inicial, entrada elétrica, aterramentos, eletrodutos, quadros e SPDA inicial.', 'Infraestrutura elétrica/SPDA fase 01 executada.', 'Relatório técnico, fotos, diário de obra e check-list das instalações executadas.', 'Fiscalização', '2026-10-31', 150000, 130000, 20000, 15000, 0.0366, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-09'), 'E16', 'Fornecimento + execução', '2026-10-01', '2026-11-30', 40000, 'Pendente', 6, 'Steel Deck', 'Fornecimento e execução de steel deck', 'Fornecimento de chapas, pinos, armaduras, concretagem e execução de laje steel deck.', 'Steel deck executado conforme avanço físico.', 'NF/romaneio, fotos, diário de concretagem, relatório de avanço físico.', 'Fiscalização', '2026-11-30', 285000, 245000, 40000, 28500, 0.061, null, null, 'Contraproposta: absorve R$ 35k da cobertura realocados do M5.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-10'), 'E17', 'Fornecimento + execução', '2026-10-01', '2026-11-30', 35000, 'Pendente', 6, 'Vedação Externa', 'Fornecimento e montagem de vedação externa', 'Isopainéis, fechamentos metálicos, vedações laterais, arremates e acessórios.', 'Vedação externa executada conforme área medida.', 'NF/romaneio, fotos, relatório de área executada e aceite parcial.', 'Fiscalização', '2026-11-30', 255000, 220000, 35000, 25500, 0.0622, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-08'), 'E18', 'Percentual físico', '2026-10-01', '2026-11-30', 55000, 'Pendente', 6, 'Instalações Gerais', 'Instalações hidrossanitárias, drenagem e incêndio', 'Água fria, esgoto, drenagem, pluvial, combate a incêndio, gás e complementos de instalações.', 'Instalações hidrossanitárias/drenagem/incêndio executadas por percentual validado.', 'Relatório técnico, fotos, testes parciais e diário de obra.', 'Fiscalização', '2026-11-30', 185000, 130000, 55000, 18500, 0.0451, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-11'), 'E19', 'Evento físico/documental', '2026-10-01', '2026-11-30', 60000, 'Pendente', 6, 'Estrutura/Cobertura/Transporte', 'Logística, transporte e conclusão de montagem', 'Fretes estruturais, entrega de materiais, ajustes de montagem, travamentos e arremates estruturais.', 'Logística e conclusão de montagem comprovadas por romaneio e fotos.', 'CT-e/NF, romaneios, fotos, relatório logístico e check-list de montagem.', 'Fiscalização', '2026-11-30', 95000, 35000, 60000, 9500, 0.0256, null, null, 'Contraproposta: ajuste de R$ 105k para R$ 95k.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-12'), 'E20', 'Percentual físico', '2026-11-01', '2026-12-31', 80000, 'Pendente', 7, 'Piso Industrial', 'Execução de piso industrial', 'Piso industrial armado, preparo de base, concretagem, acabamento superficial e juntas.', 'Piso industrial executado conforme área liberada.', 'Relatório de concretagem, fotos, diário de obra e check-list de liberação.', 'Fiscalização', '2026-12-31', 260000, 180000, 80000, 26000, 0.0634, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-13'), 'E21', 'Percentual físico', '2026-11-01', '2026-12-31', 55000, 'Pendente', 7, 'Pintura', 'Pintura industrial e demarcações', 'Pintura de superfícies metálicas, demarcações, acabamentos de pintura e correções.', 'Pintura e demarcações executadas conforme área medida.', 'Fotos, relatório de área executada, check-list de acabamento e aceite parcial.', 'Fiscalização', '2026-12-31', 205000, 150000, 55000, 20500, 0.05, null, null, null)
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-14'), 'E22', 'Percentual físico', '2026-11-01', '2026-12-31', 105000, 'Pendente', 7, 'Instalações / Acabamentos', 'Instalações finais e arremates executivos', 'Finalização de instalações, arremates, testes parciais, correções e preparação para comissionamento.', 'Instalações finais e arremates executados conforme check-list.', 'Relatório técnico, fotos, diário de obra e check-list de pendências.', 'Fiscalização', '2026-12-31', 175000, 70000, 105000, 17500, 0.0317, null, null, 'Contraproposta: aumentado de R$ 130k para R$ 175k.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-15'), 'E23', 'Evento físico', '2026-12-01', '2027-01-31', 55000, 'Pendente', 8, 'Acabamentos / Testes', 'Finalizações executivas e testes operacionais', 'Ajustes finais, pinturas finais, testes de instalações, comissionamento e correções operacionais.', 'Testes operacionais e finalizações validados.', 'Relatório de testes, check-list de comissionamento, fotos e lista de pendências.', 'Fiscalização / Contratante', '2027-01-31', 215000, 160000, 55000, 21500, 0.0524, null, null, 'Contraproposta: mantido em R$ 215k.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-16'), 'E24', 'Evento físico', '2026-12-01', '2027-01-31', 65000, 'Pendente', 8, 'Acabamentos / Pré-entrega', 'Pré-entrega e fechamento de pendências', 'Pré-entrega técnica, ajustes finais, validações de campo, arremates e liberação para entrega final.', 'Pré-entrega e fechamento de pendências validados.', 'Check-list de pré-entrega, relatório fotográfico e aceite parcial.', 'Contratante / Fiscalização', '2027-01-31', 245000, 180000, 65000, 24500, 0.0415, null, null, 'Contraproposta: aumentado de R$ 170k para R$ 245k.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;
insert into measurement (organization_id, project_id, service_id, number, kind, period_start, period_end, amount, status, month_no, stage, title, scope, criteria, documents, approver, planned_on, gross_amount, direct_amount, contractor_amount, retention_amount, planned_progress, measured_on, entry_id, notes)
values ((select id from organization where code = 'EIFF'), (select id from project where code = 'OB-SF-CL-01'), (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-17'), 'E25', 'Entrega final', '2027-01-01', '2027-02-28', 150000, 'Pendente', 9, 'Entrega Final', 'Entrega técnica, limpeza final e desmobilização', 'Limpeza final, entrega documental, as built, desmobilização e termo de entrega técnica.', 'Termo de entrega técnica emitido.', 'Termo de entrega, as built, check-list final, relatório fotográfico e documentação de encerramento.', 'Contratante', '2027-02-28', 337000, 187000, 150000, 33700, 0.0463, null, null, 'Contraproposta: aumentado de R$ 190k para R$ 337k.')
on conflict (project_id, number) do update set service_id = excluded.service_id, stage = excluded.stage, title = excluded.title, gross_amount = excluded.gross_amount, direct_amount = excluded.direct_amount, contractor_amount = excluded.contractor_amount, retention_amount = excluded.retention_amount, planned_on = excluded.planned_on;

-- religa as receitas previstas da planilha aos servicos do cronograma (pelo nome)
update financial_entry e set service_id = (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-06') where e.project_id = (select id from project where code = 'OB-SF-CL-01') and e.description ilike '%estrutura met%';
update financial_entry e set service_id = (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-13') where e.project_id = (select id from project where code = 'OB-SF-CL-01') and e.description ilike '%pintura%';
update financial_entry e set service_id = (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-07') where e.project_id = (select id from project where code = 'OB-SF-CL-01') and e.description ilike '%telha%';
update financial_entry e set service_id = (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-12') where e.project_id = (select id from project where code = 'OB-SF-CL-01') and e.description ilike '%concreto piso%';
update financial_entry e set service_id = (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and code = 'SFCL-09') where e.project_id = (select id from project where code = 'OB-SF-CL-01') and e.description ilike '%steel deck%';
update financial_entry e set service_id = null where e.project_id = (select id from project where code = 'OB-SF-CL-01') and e.service_id in (select id from project_service where project_id = (select id from project where code = 'OB-SF-CL-01') and active = false);
