-- Vinculo dos itens do orcamento ORC-328 a composicoes/insumos do SINAPI (catalogo da migration 0019). Idempotente.
-- Insumos usados diretamente viram composicoes proprias INS-<codigo> com um unico item (coeficiente 1).
insert into catalog_composition (organization_id, source, code, description, unit, group_name, notes, active)
select (select id from organization where code = 'EIFF'), 'Própria', 'INS-10775', 'Insumo SINAPI ' || i.code || ': ' || i.description, i.unit, 'Insumo direto', 'Composição-embrulho gerada para usar o insumo diretamente no orçamento.', true
from catalog_input i where i.organization_id = (select id from organization where code = 'EIFF') and i.source = 'SINAPI' and i.code = '10775'
on conflict (organization_id, source, code) do update set description = excluded.description, unit = excluded.unit;
delete from catalog_composition_item where composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-10775');
insert into catalog_composition_item (composition_id, item_order, input_id, coefficient)
select c.id, 1, i.id, 1 from catalog_composition c join catalog_input i on i.organization_id = c.organization_id and i.source = 'SINAPI' and i.code = '10775'
where c.organization_id = (select id from organization where code = 'EIFF') and c.source = 'Própria' and c.code = 'INS-10775';
insert into catalog_composition (organization_id, source, code, description, unit, group_name, notes, active)
select (select id from organization where code = 'EIFF'), 'Própria', 'INS-10778', 'Insumo SINAPI ' || i.code || ': ' || i.description, i.unit, 'Insumo direto', 'Composição-embrulho gerada para usar o insumo diretamente no orçamento.', true
from catalog_input i where i.organization_id = (select id from organization where code = 'EIFF') and i.source = 'SINAPI' and i.code = '10778'
on conflict (organization_id, source, code) do update set description = excluded.description, unit = excluded.unit;
delete from catalog_composition_item where composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-10778');
insert into catalog_composition_item (composition_id, item_order, input_id, coefficient)
select c.id, 1, i.id, 1 from catalog_composition c join catalog_input i on i.organization_id = c.organization_id and i.source = 'SINAPI' and i.code = '10778'
where c.organization_id = (select id from organization where code = 'EIFF') and c.source = 'Própria' and c.code = 'INS-10778';
insert into catalog_composition (organization_id, source, code, description, unit, group_name, notes, active)
select (select id from organization where code = 'EIFF'), 'Própria', 'INS-4813', 'Insumo SINAPI ' || i.code || ': ' || i.description, i.unit, 'Insumo direto', 'Composição-embrulho gerada para usar o insumo diretamente no orçamento.', true
from catalog_input i where i.organization_id = (select id from organization where code = 'EIFF') and i.source = 'SINAPI' and i.code = '4813'
on conflict (organization_id, source, code) do update set description = excluded.description, unit = excluded.unit;
delete from catalog_composition_item where composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-4813');
insert into catalog_composition_item (composition_id, item_order, input_id, coefficient)
select c.id, 1, i.id, 1 from catalog_composition c join catalog_input i on i.organization_id = c.organization_id and i.source = 'SINAPI' and i.code = '4813'
where c.organization_id = (select id from organization where code = 'EIFF') and c.source = 'Própria' and c.code = 'INS-4813';
insert into catalog_composition (organization_id, source, code, description, unit, group_name, notes, active)
select (select id from organization where code = 'EIFF'), 'Própria', 'INS-123', 'Insumo SINAPI ' || i.code || ': ' || i.description, i.unit, 'Insumo direto', 'Composição-embrulho gerada para usar o insumo diretamente no orçamento.', true
from catalog_input i where i.organization_id = (select id from organization where code = 'EIFF') and i.source = 'SINAPI' and i.code = '123'
on conflict (organization_id, source, code) do update set description = excluded.description, unit = excluded.unit;
delete from catalog_composition_item where composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-123');
insert into catalog_composition_item (composition_id, item_order, input_id, coefficient)
select c.id, 1, i.id, 1 from catalog_composition c join catalog_input i on i.organization_id = c.organization_id and i.source = 'SINAPI' and i.code = '123'
where c.organization_id = (select id from organization where code = 'EIFF') and c.source = 'Própria' and c.code = 'INS-123';
insert into catalog_composition (organization_id, source, code, description, unit, group_name, notes, active)
select (select id from organization where code = 'EIFF'), 'Própria', 'INS-1525', 'Insumo SINAPI ' || i.code || ': ' || i.description, i.unit, 'Insumo direto', 'Composição-embrulho gerada para usar o insumo diretamente no orçamento.', true
from catalog_input i where i.organization_id = (select id from organization where code = 'EIFF') and i.source = 'SINAPI' and i.code = '1525'
on conflict (organization_id, source, code) do update set description = excluded.description, unit = excluded.unit;
delete from catalog_composition_item where composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-1525');
insert into catalog_composition_item (composition_id, item_order, input_id, coefficient)
select c.id, 1, i.id, 1 from catalog_composition c join catalog_input i on i.organization_id = c.organization_id and i.source = 'SINAPI' and i.code = '1525'
where c.organization_id = (select id from organization where code = 'EIFF') and c.source = 'Própria' and c.code = 'INS-1525';
insert into catalog_composition (organization_id, source, code, description, unit, group_name, notes, active)
select (select id from organization where code = 'EIFF'), 'Própria', 'INS-43126', 'Insumo SINAPI ' || i.code || ': ' || i.description, i.unit, 'Insumo direto', 'Composição-embrulho gerada para usar o insumo diretamente no orçamento.', true
from catalog_input i where i.organization_id = (select id from organization where code = 'EIFF') and i.source = 'SINAPI' and i.code = '43126'
on conflict (organization_id, source, code) do update set description = excluded.description, unit = excluded.unit;
delete from catalog_composition_item where composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-43126');
insert into catalog_composition_item (composition_id, item_order, input_id, coefficient)
select c.id, 1, i.id, 1 from catalog_composition c join catalog_input i on i.organization_id = c.organization_id and i.source = 'SINAPI' and i.code = '43126'
where c.organization_id = (select id from organization where code = 'EIFF') and c.source = 'Própria' and c.code = 'INS-43126';
insert into catalog_composition (organization_id, source, code, description, unit, group_name, notes, active)
select (select id from organization where code = 'EIFF'), 'Própria', 'INS-10997', 'Insumo SINAPI ' || i.code || ': ' || i.description, i.unit, 'Insumo direto', 'Composição-embrulho gerada para usar o insumo diretamente no orçamento.', true
from catalog_input i where i.organization_id = (select id from organization where code = 'EIFF') and i.source = 'SINAPI' and i.code = '10997'
on conflict (organization_id, source, code) do update set description = excluded.description, unit = excluded.unit;
delete from catalog_composition_item where composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-10997');
insert into catalog_composition_item (composition_id, item_order, input_id, coefficient)
select c.id, 1, i.id, 1 from catalog_composition c join catalog_input i on i.organization_id = c.organization_id and i.source = 'SINAPI' and i.code = '10997'
where c.organization_id = (select id from organization where code = 'EIFF') and c.source = 'Própria' and c.code = 'INS-10997';
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '90777') where code = '1.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '93572') where code = '1.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '100309') where code = '1.4' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '94296') where code = '1.5' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-10775') where code = '2.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-10778') where code = '2.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-4813') where code = '2.10' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '99059') where code = '2.12' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '98525') where code = '2.13' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '104738') where code = '3.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '100900') where code = '4.1.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96531') where code = '4.1.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92915') where code = '4.1.3' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92919') where code = '4.1.4' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96544') where code = '4.1.6' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '103673') where code = '4.1.8' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '100900') where code = '4.6.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96531') where code = '4.6.3' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96533') where code = '4.6.4' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92269') where code = '4.6.5' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92271') where code = '4.6.6' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96557') where code = '4.6.7' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96557') where code = '4.6.8' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '103672') where code = '4.6.9' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '103674') where code = '4.6.10' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '103686') where code = '4.6.11' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96544') where code = '4.6.12' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '95944') where code = '4.6.13' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92769') where code = '4.6.14' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '104108') where code = '4.6.15' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92759') where code = '4.6.16' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '95945') where code = '4.6.17' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92770') where code = '4.6.18' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92761') where code = '4.6.19' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '96546') where code = '4.6.20' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92771') where code = '4.6.21' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92762') where code = '4.6.22' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92763') where code = '4.6.23' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '92915') where code = '4.6.24' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '89480') where code = '4.6.25' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '105033') where code = '4.6.26' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '98557') where code = '5.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-123') where code = '5.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '102107') where code = '6.1.1.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '100606') where code = '6.1.1.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '102679') where code = '6.2.4' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '103914') where code = '7.11' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-1525') where code = '8.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '103673') where code = '8.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '97086') where code = '8.3' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-43126') where code = '8.4' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '97088') where code = '8.5' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-10997') where code = '8.6' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'Própria' and code = 'INS-10997') where code = '10.4' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '94213') where code = '11.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '94216') where code = '12.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '94229') where code = '12.4' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '100757') where code = '13.1' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '102507') where code = '13.2' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
update estimate_item set composition_id = (select id from catalog_composition where organization_id = (select id from organization where code = 'EIFF') and source = 'SINAPI' and code = '88426') where code = '13.3' and estimate_id = (select id from estimate where organization_id = (select id from organization where code = 'EIFF') and code = 'ORC-328');
